# Generated by Django 3.2.5 on 2022-06-26 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4, message='Enter a valid name')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=240)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=240)),
                ('specialization', models.CharField(max_length=240)),
                ('course_type', models.CharField(max_length=240)),
                ('college', models.CharField(max_length=240)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('year_of_passing', models.IntegerField(null=True)),
                ('skills', models.CharField(max_length=240, null=True)),
                ('summary', models.TextField(null=True)),
                ('experience_level', models.CharField(max_length=240, null=True)),
                ('designation', models.CharField(max_length=240, null=True)),
                ('responsibilities', models.TextField(null=True)),
                ('company', models.CharField(max_length=240, null=True)),
                ('location', models.CharField(max_length=240, null=True)),
                ('worked_from', models.DateField(null=True)),
                ('to', models.DateField(null=True)),
                ('about_company', models.TextField(null=True)),
                ('website', models.URLField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
