# Generated by Django 3.2.5 on 2022-06-26 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4, message='Enter a valid name')]),
        ),
    ]
