# Generated by Django 3.2.5 on 2022-06-28 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220626_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('^[A-za-z0-9]+@[a-z]+.[a-z]+$', 'Enter a valid email')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator('^[7,8,9][0-9]{9}$', 'Enter a valid number')]),
        ),
    ]
