# Generated by Django 3.2.5 on 2022-06-28 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220628_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{4,}$', 'Enter a valid name')]),
        ),
    ]
