# Generated by Django 3.2.5 on 2022-06-28 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('^[A-za-z0-9]+@[a-z]+.[a-z]+$', ['Enter a valid email'])]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator('^[7,8,9][0-9]{9}$', ['Enter a valid number'])]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{4,}$', ['Enter a valid name'])]),
        ),
    ]
