# Generated by Django 3.2.5 on 2022-06-28 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('^[A-za-z0-9]+@[a-z]+.[a-z]+$', ['Enter a valid email'])]),
        ),
    ]
