# Generated by Django 3.2.5 on 2022-06-28 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220629_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\.-]+@([\\w-]+\\.)+[\\w-]{2,4}$', ['Enter a valid email'])]),
        ),
    ]
