# Generated by Django 3.2.5 on 2022-06-26 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=240)),
                ('company', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=240)),
                ('work_location', models.CharField(max_length=240)),
                ('employment_type', models.CharField(max_length=240)),
                ('qualification', models.CharField(max_length=240)),
                ('about_company', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('openings', models.IntegerField()),
                ('no_of_applicants', models.IntegerField()),
                ('application_deadline', models.DateField()),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=240)),
                ('company', models.CharField(max_length=240)),
                ('applicant_name', models.CharField(max_length=240)),
                ('applicant_email', models.CharField(max_length=240)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobdetails')),
            ],
        ),
    ]
