# Generated by Django 3.2.5 on 2022-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='no_of_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
